### PR TITLE
Adding the Quantum Design PPMS

### PR DESCRIPTION
**Pull request by cjermain**
This PR adds the Quantum Design Physical Properties Measurement System, based on the work of @guenp in [PyQDInstrument](https://github.com/guenp/PyQDInstrument).

### CODE REVIEW

**Comment by cjermain** [comment]
Since we are transitioning instruments to InstrumentKit (#53, #94), new instruments will not be accepted.

**Comment by bilderbuchi** [comment]
I'm not the maintainer of course, but wouldn't it be better to adopt a no-new-instruments policy only when we can already use IK instruments in pymeasure? This way contributors will have a chance to get stuff they need integrated by just sending a PR to IK instead.

**Comment by cjermain** [comment]
@bilderbuchi, I don't have the bandwidth currently to maintain new instruments or to finish this PR. If you are interested to do code reviews for new instrument PRs, I am happy to merge them.

**Comment by bilderbuchi** [comment]
All clear, thank you for clarifying. ☺ I'll see what I can do, but hopefully I can take a stab at integrating ik first.

**Comment by bilderbuchi** [comment]
Also, sorry, I didn't want to come across as pushy, I know how hard it is to contribute to OSS with very limited bandwidth.

**Comment by guenp** [comment]
@cjermain I can work with @ndr37 to make a PR to instrumentKit for the PPMS.

**Comment by cjermain** [comment]
@bilderbuchi, thanks. I'm looking forward to the IK integration.

@guenp and @ndr37, go team! That would be awesome.

**Comment by bilderbuchi** [comment]
Deleted the branch cause the work was not complete, so reopening and merging would not have been possible.

**Pull request closed without merging**
