### PR TITLE
Fix issues in pymeasure.instruments

### PR DESCRIPTION
**Pull request by feinsteinben**
1. Create new file with base errors.
2. Make sure imports are always at the top of the file, before any other code (also clears IDE from yellow warnings).
3. Fix pep8 compatibility (spaces, blank lines, indentations).
4. Replace mutable default values (`values=[]`) with immutable alternative (`values=()`).
5. Replace `type(<var>) is <type>` with `isinstance(<var>, <type>)`.
6. Replace `super(...)` with the new `super()`. (see: https://github.com/ralph-group/pymeasure/pull/87#issuecomment-311655493)  [previously: Replace `super(...)` with direct reference to the super-class. This is in par with the way [CPython](https://github.com/python/cpython) is written.]
7. Replace three single-quotes with three double-quotes for documentation (for consistency, and also to clear yellow warnings in IDE).
8. Replace blank `except:` statements with `except Exception:` or with more specific exceptions.
9. Replace `b <= c and b >= a` kind of conditions with `a <= b <= c`.

### CODE REVIEW

**Comment by cjermain** [comment]
@feinsteinben, please add a PR description to outline your changes and use a descriptive title that is specific to what you are accomplishing here. This is necessary for code review. Same goes for #87.

**Comment by feinsteinben** [comment]
Hi @cjermain ,

Sorry for the lack of description. It's my bad.

I updated the PR description. I thought it would be good to squash all these changes into a single PR, but maybe I got the wrong decision.

Anyway, I tried to find a more specific and descriptive name for this PR, but since it includes several types of changes - it couldn't find a good name. Do you have any suggestions?

Thanks,
Ben.

PS. Thanks for this excellent package, and all the hard work you've put in writing it and maintaining it!

**Comment by cjermain** [comment]
@feinsteinben, thanks for adding the descriptions. In the future, don't worry about squashing commits, since we typically do that on the merge. 

With regards to the `super` calls, I agree with @bilderbuchi in #87 that we should stick with the `super` calls instead of direct parent class calls. This is important for dealing with multi-class inheritance and mixin classes, and as a convention `super` is the preferred method to my knowledge. Please revert those changes.

Otherwise this PR looks great! Thanks for getting PyMeasure up to standard!

**Comment by bilderbuchi** [comment]
Great work spotting nr. 4, btw! Mutable default values is a frequent and potentially dangerous mistake.

**Comment by feinsteinben** [comment]
Thanks for the review. Squashed this change into PR  #85.
Think it can be closed.

**Pull request closed without merging**
