### PR TITLE
Updating license year to 2019

### LINKED ISSUE #176: Update the license year
This issue tracks updating the license year across the code-base, so that it is up to date.

### PR DESCRIPTION
**Pull request by cjermain**
This PR resolves #176, by updating the license year to 2019.

### CODE REVIEW

**Comment by cjermain** [comment]
I pinned the `pytest` and `pytest-qt` version to ensure that they work together properly.

**Comment by bilderbuchi** [comment]
What did you observe where pytest and pytest-qt did not work together properly?

**Comment by cjermain** [comment]
See the CI for https://github.com/ralph-group/pymeasure/pull/188/commits/ec6935570b0f5e235210495ccbb62f2157cd9c89.

**Comment by bilderbuchi** [comment]
@cjermain I think I found a more relaxed set of version specifiers for this problem, PR incoming.

**Pull request merged**
