### PR TITLE
Enhancing unit tests

### PR DESCRIPTION
**Pull request by cjermain**
This PR enhances the unit tests available to PyMeasure on the non-instruments code. It seeks to solve #92 and ensure that example code is tested in CI.

### CODE REVIEW

**Comment by cjermain** [comment]
This is a work in progress, with more needed on the `pymeasure.experiment` tests and tests to ensure that the examples run without errors. I plan to release a new minor release when this is finished.

**Comment by bilderbuchi** [comment]
:+1:

**Comment by bilderbuchi** [comment]
One thing that could be useful in increasing test coverage would be to add `sphinx doctest` to the CI scripts, and adapt code in the docs to run as doctests. This does not always make sense, due to this package's close connection with hardware. However, in the [adding instruments](http://pymeasure.readthedocs.io/en/latest/dev/adding_instruments.html) section, which is nearly testable already, it could be feasible to redefine the "Extreme 5000" as a `FakeInstrument` under the hood (non-user-visible) using a [test-setup](http://www.sphinx-doc.org/en/stable/ext/doctest.html#directive-testsetup) directive. This way, conceivably the whole section could be run as a doctest.
Also, see https://github.com/ralph-group/pymeasure/issues/98#issuecomment-317273099.

**Comment by cjermain** [comment]
@bilderbuchi, I like the Sphinx doctest idea. Let's hold off on it for another PR and continue discussion in #98.

**Comment by bilderbuchi** [comment]
Sure :-)

**Comment by cjermain** [comment]
I've removed setting `spawn`, to allow Unix platforms to use `fork`. This solves #105, which were being caused by an issue in the [semaphore cleanup method](https://github.com/python/cpython/blob/48350412b70c76fa51f488cfc736c80d59b5e8eb/Lib/multiprocessing/synchronize.py#L87). This branch needs to confirm that results are being written to the temp file in `test_worker_finish` (looks like this is failing on Windows and needs debugging). I would also like to add better coverage to the `Results` class before merging. Still a work in progress...

**Pull request merged**
