### PR TITLE
One-liner typo fix in SR830 instrument

### PR DESCRIPTION
**Pull request by dennisfeng2**
The time constants values in the SR830 increase like so: 10e-6, 30e-6, 100e-6, 300e-6, 1e-3, etc. 
The list was just missing a `30`.

### CODE REVIEW

**Comment by dennisfeng2** [comment]
I've noticed that there are some failed tests/checks with this pull request, but after taking a look at the error messages, it's still unclear to me whether these issues are coming from bugs in the pull request itself. For example, some of the errors involve import errors of VXI11Adapter and HP34410A, which my code doesn't seem to touch at all. Could someone point out to me why these errors are occurring, or anything I can fix from my end, so we can make progress on this PR?

**Comment by cjermain** [comment]
@dennisfeng2, thanks for putting up this PR. I've restarted the CI tests, and will investigate further if they continue to fail.

**Comment by cjermain** [comment]
It looks like there are a few build errors that have cropped up. I'll fix them when I have the opportunity.

**Comment by cjermain** [comment]
Please merge the latest master branch into yours to fix the Travis CI build failure.

**Comment by dennisfeng2** [comment]
Apologies for the late response. Finished merging the latest master branch!

**Comment by cjermain** [comment]
Thanks @dennisfeng2!

**Pull request merged**
