### PR TITLE
Instrument Anritsu ms9710c

### PR DESCRIPTION
**Pull request by TvBMcMaster**
A new Anritsu MS9710C Optical Spectrum Analyzer Instrument.

* setting and reading scanning wavelength parameters
* setting and reading power parameters
* setting and reading sweep parameters
* setting and reading analysis peak search parameters
* read the data memory registers
* setting and reading of analysis trace markers
* some helper methods to perform sweeps and peak measurements

Also includes a new validator helper for joining multiple validators together, with tests.

### CODE REVIEW

**Comment by TvBMcMaster** [comment]
The build is failing, though it does not seem related to any of the code changes.  

Can a build of the master branch be forced to verify?

**Comment by TvBMcMaster** [comment]
Actually, looking back at the Appveyor [build history](https://ci.appveyor.com/project/cjermain/pymeasure/history), it seems to have broken between build 0.3.169 and 0.3.170.  

The error is a version mismatch between some py34 conda dependencies on win32 systems.  
    
    UnsatisfiableError: The following specifications were found to be in conflict:
      - pyqt 4.11.4 py34_4 -> sip >=4.16.4,<4.18
      - sip 4.18 py34_0
    Use "conda info <package>" to see the dependencies for each package.

I will create a new issue for this.

**Comment by cjermain** [comment]
Nice work @TvBMcMaster! I've fixed the CI issues. Can you [add the instrument to the docs](http://pymeasure.readthedocs.io/en/latest/dev/adding_instruments.html#adding-documentation)?

I like the `joined_validators` function that you added.

**Comment by cjermain** [comment]
Thanks!

**Pull request merged**
