### PR TITLE
Use conda-forge instead of pip packages in CI.

### PR DESCRIPTION
**Pull request by bilderbuchi**
This should make sure that we really use the pytest version specified.

### CODE REVIEW

**Comment by bilderbuchi** [comment]
I don't know why Travis crashes on this one build. A rerun of the test did not fix this.
Comparing https://travis-ci.org/ralph-group/pymeasure/jobs/523174765#L752 and the failing https://travis-ci.org/ralph-group/pymeasure/jobs/525675142#L741 the only differences are in the pytest and related package versions.

**Comment by cjermain** [comment]
@bilderbuchi, thanks for putting up this PR. The CI issue appears to be localized to Python 3.5 on Linux only. I'll take a further look when I get more time.

**Comment by cjermain** [comment]
Please merge the latest master branch into yours to fix the Travis CI build failure.

**Comment by bilderbuchi** [comment]
@cjermain merged master, it is still failing.

**Comment by cjermain** [comment]
Interesting. I re-triggered the build, and it is still failing. The `xvfb` fix is working, because I can see that service is running. The tests are also definitely failing in the Qt section, so it is a GUI issue. I'm not sure why the conda-forge versions might differ.

**Comment by cjermain** [comment]
I used these ideas in #211, which fixes the builds and adds conda-forge as a channel. Thanks @bilderbuchi!

**Comment by bilderbuchi** [comment]
Great, glad that it helped!

**Pull request closed without merging**
