### PR TITLE
SR 830 instrument property additions

### PR DESCRIPTION
**Pull request by dennisfeng2**
Here, I add some more controllable settings to the SR 830 instrument. I've also tested them on the instrument.

### CODE REVIEW

**Comment by dennisfeng2** [comment]
I've noticed that there are some failed tests/checks with this pull request, but after taking a look at the error messages, it's still unclear to me whether these issues are coming from bugs in the pull request itself. For example, some of the errors involve import errors of VXI11Adapter and HP34410A, which my code doesn't seem to touch at all. Could someone point out to me why these errors are occurring, or anything I can fix from my end, so we can make progress on this PR?

**Comment by cjermain** [comment]
Please merge the latest master branch into yours to fix the Travis CI build failure.

**Comment by dennisfeng2** [comment]
Apologies for the late response. Finished merging the latest master branch!

**Comment by cjermain** [comment]
Great addition @dennisfeng2!

**Pull request merged**
