### PR TITLE
Add instructions on how to install with conda

### PR DESCRIPTION
**Pull request by melund**
I  have added instructions on how to install with conda. 

I think the install instructions would be simpler if you didn't suggest doing the install through a notebook. I haven't changed that though...

### CODE REVIEW

**Comment by cjermain** [comment]
Please correct the package name and remove the ">" characters from the commands. 

I wrote the instructions for the notebook to allow beginners to install and test the package in the same environment, and introduce the "!" command that I think is very handy for Windows users. I assume more advanced users can get it installed on their own. I'm open to suggestions for improving the instructions though.

**Comment by melund** [comment]
Done. 

Finding the best way to target beginner is extremely tricky. That is also my experience. So maybe you are onto something with the notebook approach. Although I guess most users trying PyMeasure would know what a command prompt/terminal is. 

I have had some luck creating a tutorial as a Jupyter Notebook for one of my first projects. https://github.com/AnyBody-Research-Group/AnyPyTools/blob/master/Tutorial/00_AnyPyTools_tutorial.ipynb

The cool thing about that approach is that I could bundle the tutorial with the conda package. So users would get a live version of the tutorial after installing my package with conda.

**Comment by cjermain** [comment]
I've had a chance to run the instructions in the notebook, and found it requires the `--yes` argument.
```
!conda config --add channels conda-forge
!conda install pymeasure --yes
```
The print out is pretty badly formatted, so I don't think that conda in the notebook is worth pointing people towards as @melund mentioned. Since its preferred that people move to the [in-place installation](http://pymeasure.readthedocs.io/en/latest/dev/contribute.html#using-the-development-version) (`pip install -e .`) version for contributing features, I want to keep this consistent. For now, lets keep the pip instruction, and add a sub-section of "Installing PyMeasure" that briefly describes the alternative installation using conda-forge.

@ddale, do you have any thoughts on the best way to instruct beginners to install the package?

**Comment by melund** [comment]
You are right. IPython and the notebook, in particular, is not well suited for working with CLI's like pip or conda. And in general, it is not the best practice to introduce to new users. Let them install PyMeasure from the command line. 

I am not a big fan of `pip`.  And suggesting people to use `pip` with the anaconda python distribution is a terrible idea. `Conda` will not know of the packages that were pip-installed and you can easily end in a situation where the dependencies of PyMeasure are suddenly broken when users install something else. 

I guess `pip install -e` is the new `python setup.py develop`. That is the only use of pip that makes sense when you are using the Anaconda python distribution. 

I would really suggest that you just make the instructions for different scenarios. The first one could be targeted, beginners. I.e. Anaconda python distribution and the conda commands.  The second one could be installing with pip for people who don't want to use Anaconda.

**Comment by ddale** [comment]
I agree with all of this.

**Comment by ddale** [comment]
> 
> @ddale, do you have any thoughts on the best way to instruct beginners to install the package?
> 

I think the easiest way for beginners is to use Anaconda Navigator: https://docs.continuum.io/anaconda/navigator. I'll look into supporting it on Monday.

**Comment by melund** [comment]
@ddale. That is a good option for non-tech users. It is also very easy to do. All that is needed is to add an `app` section to the recipe. See how we do it for xonsh. https://github.com/conda-forge/xonsh-feedstock/blob/master/recipe/meta.yaml#L41

The only downside is that the navigator is still a little unfinished. Icon and the detailed descriptions don't work but should be fixed soon. See this conversation: https://github.com/ContinuumIO/anaconda-issues/issues/937#issuecomment-234980373

**Comment by cjermain** [comment]
Thats a good idea @ddale, but I agree with @melund that Navigator is not that polished. It may be a good solution in the future when it comes out of beta. 

@melund, can you update the docs to use the "Anaconda prompt" and conda instructions? Please make sure to correct the package to `pymeasure`.

**Comment by melund** [comment]
@cjermain I have updated the instruction. Hope this is better

**Comment by cjermain** [comment]
@melund, thanks!

**Pull request merged**
