### PR TITLE
Adding Agilent 34410A Multimeter

### PR DESCRIPTION
**Pull request by dvspirito**
This request is to add a class for Agilent 34410 multimeter. It is a very simple implementation in its current status.

Note:
I've been using Pymeasure in the last months, writing Instrument classes for the equipment I use. I did only very simple classes to cover my needs. Lately I had sometime to review the code and decided to bring them to github.
So, I'm going to open some pull request in a short time. Although the Instruments are not fully developed, I think it would be useful to discuss with developers and users to see what is more interesting ore needed.

### CODE REVIEW

**Comment by cjermain** [comment]
@dvspirito, thanks for opening this PR and contributing code for the Agilent 34410! I'm also glad to hear you are having success with PyMeasure.

The continuous integration (CI) checks are failing for the PR because the file should be `agilent34410A.py` instead of `agilent34410a.py`. This will fix the import error and allow Python to find `agilent.agilent34410A`.

Please [add a corresponding documentation page](http://pymeasure.readthedocs.io/en/latest/dev/adding_instruments.html#adding-documentation) for this instrument before it gets merged. Can you expand the doc tags for the Instrument.measurements to describe their units?

**Comment by cjermain** [comment]
Also, please add yourself to the `AUTHORS.txt` file.

**Comment by dvspirito** [comment]
@cjermain thanks for the reply and the help. I did the required fixes.

**Comment by cjermain** [comment]
Looks good. Thanks @dvspirito!

**Pull request merged**
