### PR TITLE
Install the tests alongside the package

### LINKED ISSUE #80: Consider installing the tests
Since you decided to embed the test suite inside the package instead of leaving it outside in a common `tests` folder (both of which are totally acceptable and covered by the `pytest` guidelines), why not install the tests with the package? It would give the following benefits:

- Simplify the `setuptools` metadata, by replacing the explicit listing of the modules with a single call to `find_package`,
- Easy testing of the installed package via `python -m pytest --pyargs pymeasure`.

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #80

### CODE REVIEW

**Comment by ghisvail** [comment]
Should be ready to merge now

**Comment by cjermain** [comment]
Thanks @ghisvail!

**Comment by ghisvail** [comment]
Could you push a new release to PyPI with the latest changes in? Thanks.

**Comment by cjermain** [comment]
Yes. I will do a minor release before the end of the weekend.

**Pull request merged**
